networks:
    internal:
        driver: bridge
        internal: true
volumes:
    data:
        external: true
services:
    webdav:
        build: webdav
        restart: unless-stopped
        working_dir: /data
        networks:
            - internal
        volumes:
            - data:/data
        command: --port=80 --auth=false --prefix=/webdav
