networks:
    internal:
        driver: bridge
        internal: true
volumes:
    data:
        external: true
services:
    # https://github.com/hacdias/webdav
    webdav:
        image: hacdias/webdav:v4
        restart: unless-stopped
        working_dir: /data
        networks:
            - internal
        volumes:
            - data:/data
        command: --port=80 --auth=false --prefix=/webdav
