networks:
    internal:
        driver: bridge
        internal: true
volumes:
    data:
        external: true
services:
    webdav:
        image: hacdias/webdav:v4.1.1@sha256:825bb55ba82a77b895d32b5e97775bda1b24c614bf3a6dda1b3cad89c6c15c12
        restart: unless-stopped
        working_dir: /data
        networks:
            - internal
        volumes:
            - data:/data
        command: --port=80 --auth=false --prefix=/webdav
