networks:
  internal:
    driver: bridge
    internal: true
volumes:
  data:
    external: true
services:
  webdav:
    build:
      context: .
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - data:/data