services:
# iperf3 speedtest server
  iperf3:
    restart: unless-stopped
    build: .
    ports:
      - 5201:5201/udp
      - 5201:5201/tcp
# healthcheck not needed, just wastes resources
    healthcheck:
      disable: true