services:
# iperf3 speedtest server
  iperf3:
    image: mlabbe/iperf3
    restart: unless-stopped
    ports:
      - 5201:5201/udp
      - 5201:5201/tcp
# healthcheck not needed, just wastes resources
    healthcheck:
      disable: true