volumes:
  syncthing:

# https://github.com/syncthing/syncthing/blob/main/README-Docker.md

services:
  syncthing:
    image: docker.io/syncthing/syncthing
    restart: unless-stopped
    volumes:
      - syncthing:/var/syncthing
    ports:
      - 127.0.0.1:8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
