networks:
    internal:
        driver: bridge
        internal: true
volumes:
    invidious:
        external: true
services:
    invidious:
        image: quay.io/invidious/invidious
        restart: always
        networks:
            - default
            - internal
        environment:
          # https://github.com/iv-org/invidious/issues/3854
          # is this supposed to be secret lol? todo!
          INVIDIOUS_CONFIG: |
                database_url: postgres://postgres:@postgres
                hmac_key: b7377837040574d07a254cb89b6f7e014b14386c
        depends_on:
            postgres:
                condition: service_healthy
    postgres:
        build: postgres
        restart: always
        networks:
            - internal
        volumes:
            - invidious:/var/lib/postgresql/data
        environment:
            # todo secret store? is this even needed?
            - POSTGRES_HOST_AUTH_METHOD=trust
        # postgres takes a long time to start
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 10s
            retries: 20
