volumes:
  vpn:
    external: true
  downloads:
    external: true
  qbittorrent:
    external: true
services:
  vpn:
    image: lscr.io/linuxserver/wireguard
    restart: unless-stopped
    #sysctls:
    #  - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
    #  - SYS_MODULE
    volumes:
      - vpn:/config
    #  - /lib/modules:/lib/modules
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    restart: unless-stopped
    volumes:
      - downloads:/downloads
      - qbittorrent:/config
    network_mode: service:vpn
