volumes:
  data:
  backup:
  borg:
  rclone:
services:
  nfs:
    image: erichough/nfs-server
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    privileged: true
    environment:
      NFS_EXPORT_0: '/data *(rw,fsid=0,insecure,all_squash,anonuid=0,anongid=0)'
      NFS_DISABLE_VERSION_3: true
    volumes:
      - data:/data
    ports:
      - 2049:2049
  borg:
    build: borg
    volumes:
      - data:/data
      - backup:/backup
      - borg:/borg
  rclone:
    build: rclone
    volumes:
      - backup:/backup
      - rclone:/rclone
    environment:
      - RCLONE_B2_ACCOUNT=${RCLONE_B2_ACCOUNT?you forgot ./rclone/configure.sh}
      - RCLONE_B2_KEY=${RCLONE_B2_KEY?you forgot ./rclone/configure.sh}