volumes:
  nas_data:
    external: true
  restic:
services:
  nfs:
    image: erichough/nfs-server:2.2.1@sha256:1efd4ece380c5ba27479417585224ef857006daa46ab84560a28c1224bc71e9e
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    privileged: true
    environment:
      NFS_EXPORT_0: '/data/public *(rw,fsid=0,insecure,all_squash,anonuid=0,anongid=0)'
      NFS_DISABLE_VERSION_3: true
    volumes:
      - nas_data:/data
    ports:
      - 2049:2049
  samba:
    image: dperson/samba:latest@sha256:e1d2a7366690749a7be06f72bdbf6a5a7d15726fc84e4e4f41e967214516edfd
    restart: unless-stopped
    ports:
      - 139:139
      - 445:445
    volumes:
      - nas_data:/data
    command: -s "public;/data/public;yes;no"
    environment:
      USERID: 0
      GROUPID: 0
  restic:
    build: restic
    restart: unless-stopped
    volumes:
      - nas_data:/data
      - restic:/restic
    environment:
      - RESTIC_B2_ID=${RESTIC_B2_ID?you forgot to configure restic, see README}
      - RESTIC_B2_KEY=${RESTIC_B2_KEY?you forgot to configure restic, see README}
      - RESTIC_PASSWORD=${RESTIC_PASSWORD?you forgot to configure restic, see README}
