networks:
  actualbudget_default:
    name: actualbudget_default
    external: false

volumes:
  caddy_config:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./caddy_config"

# todo disable tailscale and expose caddy to 8080
