networks:
    internal:
        driver: bridge
        internal: true
volumes:
    mail:
services:
    dovecot:
        build: dovecot
        networks:
            - internal
        volumes:
            - mail:/mail
    postfix:
        build: postfix
        networks:
            - internal
    nginx:
        build: dev/nginx
        ports:
            - 1143:143
            - 2225:25
