networks:
    internal:
        driver: bridge
        internal: true
volumes:
    mail:
    certificates:
services:
    maddy:
        build: maddy
        ports:
            # smtp (external)
            - 25:25
            # submission (starttls, this is bad)
            #- 587:587
            # submission (implict tls)
            - 465:465
            # imap (starttls, this is bad)
            #- 143:143
            # imap (implicit tls)
            - 993:993
        depends_on:
            certificates:
                condition: service_completed_successfully
        environment:
            MADDY_HOSTNAME: mx.localhost
            MADDY_DOMAIN: localhost
            TLS_CERT: /certificates/cert.pem
            TLS_KEY: /certificates/key.pem
        volumes:
            - mail:/data
            - certificates:/certificates
    # generate dummy certificate for maddy
    certificates:
        image: alpine
        entrypoint: ["sh", "-c", "cd /certificates && if [ -e 'key.pem' ]; then echo 'key already exists' && exit 0; fi && apk add openssl && openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -subj /CN=localhost -nodes"]
        volumes:
            - certificates:/certificates
#        networks:
#            - internal
#        volumes:
#            - mail:/mail
#    nginx:
#        build: dev/nginx
#        ports:
#            - 1143:143
#            - 2225:25
