volumes:
    mail:
        external: true
    http_certificates:
        external: true
services:
    maddy:
        build: maddy
        restart: unless-stopped
        ports:
            - 25:25
            - 465:465
            - 993:993
        volumes:
            - mail:/mail
            - http_certificates:/certificates:ro
        environment:
            MADDY_HOSTNAME: mx1.stzups.net
            MADDY_DOMAIN: stzups.net
            TLS_CERT: /certificates/griffinht.com/fullchain.cer
            TLS_KEY: /certificates/griffinht.com/griffinht.com.key
# todo ensure certificates exist before maddy starts
