services:
  wireguard:
    restart: unless-stopped
    image: place1/wg-access-server
    build:
      context: wireguard
    cap_add:
      - NET_ADMIN
    volumes:
      - "wg-access-server-data:/data"
    ports:
      - "123:123/udp"
      - "8000:8000/tcp"
    devices:
      - "/dev/net/tun:/dev/net/tun"

# shared volumes with the host
volumes:
  wg-access-server-data:
    driver: local
