services:
  nginx:
    depends_on:
      certbot:
        condition: service_started
      dynamic-ip:
        condition: service_started
    restart: unless-stopped
    image: nginx
    build:
      context: nginx
    ports:
#      - 80:80
      - 443:443
#    networks:
#      - default
    volumes:
      - certbot:/etc/letsencrypt/
  certbot:
    restart: unless-stopped
    image: certbot
    build:
      context: certbot
    secrets:
      - certbot_cloudflare
    volumes:
      - certbot:/etc/letsencrypt/
  dynamic-ip:
    restart: unless-stopped
    image: dynamic-ip
    build:
      context: dynamic-ip
    secrets:
        - dynamic-ip_cloudflare
    volumes:
      - ./dynamic-ip/dns-ids:/dns-ids
      - ./dynamic-ip/zone-id:/zone-id

volumes:
  certbot:

secrets:
  certbot_cloudflare:
    file: bin/certbot_cloudflare
  dynamic-ip_cloudflare:
    file: bin/dynamic-ip_cloudflare