# https://www.reddit.com/r/Piracy/comments/cuzmro/guide_how_to_set_up_docker_containers_to/
# https://gitlab.com/-/snippets/1878730

services:
# openvpn server
# for connecting outside clients
# requires setup, see
# https://github.com/kylemanna/docker-openvpn/blob/master/docs/docker-compose.md
#  openvpn:
#    cap_add:
#     - NET_ADMIN
#    image: kylemanna/openvpn
#    ports:
#     - "1194:1194/udp"
#    restart: always
#    volumes:
#     - ./openvpn-data/conf:/etc/openvpn

# samba
  samba:
    image: dperson/samba
    environment:
      - TZ=America/New_York
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /var/lib/docker/volumes/downloads:/downloads:z
    command: '-s "Downloads;/downloads" -u "bob;password"'

# nginx
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

# Jellyfin
# port 8096
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /path/to/library:/config
      - /path/to/tvseries:/data/tvshows
      - /path/to/movies:/data/movies
    restart: unless-stopped

# OpenVPN client
# can be used by other services with network_mode: service:openvpn-client
# make sure to add ports to forward on the vpn
# https://github.com/dperson/openvpn-client/blob/master/docker-compose.yml
  openvpn-client:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    environment:
      - TZ=America/New_York
    networks:
      - default
# disable when using DNS flag (-d)
    #read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    command: '-d -f \"\"'
    volumes:
      - /dev/net:/dev/net:z
      - ./bin/vpn:/vpn
    ports:
    - "5800:5800"
    - "8080:8080"
    - "7878:7878"

#
# VPN services
#
    
# Firefox with vpn, connect from a browser
# port 5800
  firefox:
    image: jlesage/firefox
    restart: always
    network_mode: service:openvpn-client
    shm_size: 2g
    volumes:
     - /var/lib/docker/volumes/firefox-config:/config:rw
     - /var/lib/docker/volumes/downloads:/downloads

# qBittorrent
# port 8080
  qbittorrent:
    image: linuxserver/qbittorrent
    restart: always
    network_mode: service:openvpn-client
    environment:
     - PUID=1000
     - PGID=1000
     - TZ=America/New_York
     - UMASK_SET=022
     - WEBUI_PORT=8080
    volumes:
     - /var/lib/docker/volumes/qbittorrent-config:/config
     - /var/lib/docker/volumes/downloads:/downloads

# Radarr
# port 7878
  radarr:
    image: linuxserver/radarr
    restart: always
    network_mode: service:openvpn-client
    environment:
     - PUID=1000
     - PGID=1000
     - TZ=America/New_York
     - UMASK_SET=022
    volumes:
     - /var/lib/docker/volumes/radarr-data:/config
     - /var/lib/docker/volumes/radarr-movies:/movies
     - /var/lib/docker/volumes/downloads:/downloads
