services:
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html/:/etc/nginx/html/
    ports:
      - 80:80
#      - 443:443
#    networks:
#      - default
