services:
  wireguard:
    image: place1/wg-access-server
    build:
       dockerfile: wireguard/Dockerfile
       context: .
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - "wg-access-server-data:/data"
      - "./wireguard/config.yaml:/config.yaml"
    ports:
      - "80:80/udp"
      - "8000:8000/tcp"
    devices:
      - "/dev/net/tun:/dev/net/tun"

# shared volumes with the host
volumes:
  wg-access-server-data:
    driver: local
