services:
  nginx:
    depends_on:
      certbot:
        condition: service_started
    restart: unless-stopped
    image: nginx
    build:
      context: nginx
    ports:
#      - 80:80
      - 443:443
#    networks:
#      - default
    volumes:
      - certbot:/etc/letsencrypt/
  certbot:
    restart: unless-stopped
    image: certbot
    build:
      context: certbot
    secrets:
      - certbot_cloudflare
    volumes:
      - certbot:/etc/letsencrypt/

volumes:
  certbot:

secrets:
  certbot_cloudflare:
    file: bin/certbot_cloudflare
