# https://www.reddit.com/r/Piracy/comments/cuzmro/guide_how_to_set_up_docker_containers_to/
# https://gitlab.com/-/snippets/1878730

networks:
  default:

services:
# openvpn server
# for connecting outside clients
# requires setup, see
# https://github.com/kylemanna/docker-openvpn/blob/master/docs/docker-compose.md
#  openvpn:
#    restart: unless-stopped
#    cap_add:
#     - NET_ADMIN
#    image: kylemanna/openvpn
#    ports:
#     - "1194:1194/udp"
#    volumes:
#     - ./openvpn-data/conf:/etc/openvpn

# samba
  samba:
    image: dperson/samba
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    networks:
    - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - downloads:/downloads:z
    command: '-n -p -s Downloads;/downloads'

# nginx
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

# Jellyfin
# port 8096
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /path/to/library:/config
      - /path/to/tvseries:/data/tvshows
      - /path/to/movies:/data/movies

# OpenVPN client
# can be used by other services with network_mode: service:openvpn-client
# make sure to add ports to forward on the vpn
# https://github.com/dperson/openvpn-client/blob/master/docker-compose.yml
  openvpn-client:
    image: dperson/openvpn-client
    restart: unless-stopped
    cap_add:
      - net_admin
    environment:
      - TZ=America/New_York
    networks:
      - default
# disable when using DNS flag (-d)
    #read_only: true
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    command: '-d -f \"\"'
    volumes:
      - /dev/net:/dev/net:z
      - ./bin/vpn:/vpn
    ports:
      - "5800:5800"
      - "8080:8080"
      - "7878:7878"

#
# VPN services
#
    
# Firefox with vpn, connect from a browser
# port 5800
  firefox:
    image: jlesage/firefox
    restart: unless-stopped
    network_mode: service:openvpn-client
    shm_size: 2g
    volumes:
      - firefox-config:/config:rw
      - downloads:/downloads

# qBittorrent
# port 8080
  qbittorrent:
    image: linuxserver/qbittorrent
    restart: unless-stopped
    network_mode: service:openvpn-client
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent-config:/config
      - downloads:/downloads

# Radarr
# port 7878
  radarr:
    image: linuxserver/radarr
    restart: unless-stopped
    network_mode: service:openvpn-client
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=022
    volumes:
      - radarr-data:/config
      - radarr-movies:/movies
      - downloads:/downloads
