services:
  traefik:
    image: traefik:v3.0
    restart: unless-stopped
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker --ping --accesslog=true --accesslog.fields.headers.defaultmode=keep --accesslog.fields.headers.names.host=keep --accesslog.fields.names.RequestHost=keep --accesslog.format=json --metrics.prometheus=true --providers.docker.exposedByDefault=false
    networks:
      - default
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

        #e2e - metrics on /metrics
