services:
  registry-write:
    ports:
      - 5000:5000
  registry-ui:
    ports:
      - 5002:80
  caddy:
    image: docker.io/caddy
    depends_on:
      - registry
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
