volumes:
  searxng_internal:

services:
    searx:
        image: searxng/searxng
        restart: always
        environment:
            - BASE_URL=https://hot.griffinht.com/searx/
        volumes:
          - searxng_internal:/etc/searxng
