services:
  hydroxide:
    build: hydroxide
    restart: unless-stopped
    command: serve
    ports: 
      - 1025
      - 1143
  nginx:
    build: nginx
    restart: unless-stopped
    ports:
      - 8080:80
