volumes:
  prometheus:
  prometheus_config:
  grafana:

networks:
  iperf_default:
    external: true

services:

  prometheus:
    image: docker.io/prom/prometheus
    restart: unless-stopped
    depends_on:
      - blackbox_exporter
    networks:
      - default
      - iperf_default 
    volumes:
      - prometheus_config:/config:ro
      - prometheus:/prometheus
    command: --config.file=/config/prometheus.yml
    extra_hosts:
      - host.docker.internal:host-gateway

  blackbox_exporter:
    image: quay.io/prometheus/blackbox-exporter:latest
    restart: unless-stopped

  # todo alertmanager

  grafana:
    image: docker.io/grafana/grafana-oss
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
