services:
  laminar:
    image: mylaminar
    volumes:
      #- ./laminar.conf:/etc/laminar.conf:ro
      - ./laminar:/var/lib/laminar
    env_file: laminar.conf
    command: laminard
    ports:
      - 127.0.0.1:9997:9997
      - 127.0.0.1:8080:8080
