networks:
    internal:
        driver: bridge
        internal: true
volumes:
    git:
        external: true
services:
    git-http-frontend:
        build: ./git-http-frontend
        restart: unless-stopped
        depends_on:
            - php
        ports:
            - 8080:80
        networks:
            - internal
    php:
        build: ./php
        restart: unless-stopped
        networks:
            - internal
        volumes:
            - git:/git:ro
