# https://github.com/shift/domain_exporter#example-prometheus-alert

groups:
 - name: ./domain.rules
   rules:
    - alert: DomainExpiring
      # todo set to like 2 years idk?
      expr: domain_expiration{} < 4500
      for: 24h
      labels:
        severity: warning
      annotations:
        description: "{{ $labels.domain }} expires in {{ $value }} days"
    - alert: DomainUnfindable
      expr: domain_expiration_unfindable > 0
      for: 24h
      labels:
        severity: critical
      annotations:
        description: "Unable to find or parse expiry for {{ $labels.domain }}"
    - alert: DomainMetricsAbsent
      expr: absent(domain_expiration) > 0
      for: 1h
      labels:
        severity: warning
      annotations:
        description: "Metrics for domain-exporter are absent"
