apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  #storageClassName: standard
---
apiVersion: v1
kind: Pod
metadata:
  name: iperf
spec:
  containers:
  - name: tailscale
    image: tailscale/tailscale
    env:
    - name: TS_KUBE_SECRET
      value: ''
    - name: TS_STATE_DIR
      value: /var/lib/tailscale
    volumeMounts:
    - name: ts-config
      mountPath: /var/lib/tailscale
  - name: iperf
    image: docker.io/griffinhtdocker/iperf
    ports:
    - containerPort: 5201
    command: 
    - iperf3
    - --server
  volumes:
  - name: ts-config
    persistentVolumeClaim:
      claimName: tailscale-config
