volumes:
  git:
    external: true

networks:
  internal:
    driver: bridge
    internal: true

services:
  griffinht:
    build: nginx
    restart: always
    depends_on:
      git:
        condition: service_started
    networks:
      - default
      - internal
  git:
    build: git
    restart: always
    networks:
      - internal
    volumes:
      - git:/git:ro
