#!/bin/sh

# public url to ci, so we can click links
url=http://localhost:8080
# alertmanager url for submitting alerts
alertmanager_url=alertmanager:9093

if [ "$RESULT" != success ]; then
    echo "$url/jobs/$JOB/$RUN failed with $RESULT" | curl \
        -X POST \
        -d @- \
        "${alertmanager_url}/post"
fi
