default_redirection_url: https://hot.griffinht.com

server:
    path: login
    # default is 4096 which isn't enough for libreddit subscription import :(
    read_buffer_size: 8192
    write_buffer_size: 8192

log:
    level: debug

totp:
    issuer: hot.griffinht.com

webauthn:
    display_name: hot.griffinht.com

duo_api:
    disable: true

# probably fine without ntp
# allows authelia to run without internet access
ntp:
    disable_startup_check: true

authentication_backend:
    file:
        path: /data/users_database.yml

access_control:
    default_policy: two_factor

regulation:
    max_retries: 3
    find_time: 2m
    ban_time: 5m

session:
    # todo restrict so not every backend server gets the session cookie
    domain: griffinht.com
    redis:
        host: redis
        port: 6379

storage:
    local:
        path: /data/db.sqlite3

notifier:
    # todo use smtp
    filesystem:
        filename: /data/notification.txt

telemetry:
    metrics:
        enabled: true
