#default_redirection_url: https://hot.localhost
#session- AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session
#jwt_secret_file: /run/secrets/authelia_jwt
#- AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/authelia_storage

server:
    path: login
    # default is 4096 which isn't enough for libreddit subscription import :(
    read_buffer_size: 8192
    write_buffer_size: 8192

log:
    level: debug

totp:
    issuer: hot.griffinht.com

webauthn:
    display_name: hot.griffinht.com

duo_api:
    disable: true

# probably fine without ntp
# allows authelia to run without internet access
ntp:
    disable_startup_check: true

authentication_backend:
    file:
        path: /data/users_database.yml

access_control:
    default_policy: two_factor

regulation:
    max_retries: 3
    find_time: 2m
    ban_time: 5m

session:
    redis:
        host: redis
        port: 6379
    secret_file: /run/secrets/authelia_session

storage:
    local:
        path: /data/db.sqlite3
    encryption_key_file: /run/secrets/authelia_storage

notifier:
    # todo use smtp
    filesystem:
        filename: /data/notification.txt

telemetry:
    metrics:
        enabled: true
