#default_redirection_url: https://hot.localhost

server:
    path: login
    # default is 4096 which isn't enough for libreddit subscription import :(
    buffers:
        read: 8192
        write: 8192

log:
    level: debug

totp:
    issuer: hot.griffinht.com

webauthn:
    display_name: hot.griffinht.com

duo_api:
    disable: true

# probably fine without ntp
# allows authelia to run without internet access
ntp:
    disable_startup_check: true

authentication_backend:
  file:
        path: /data/users_database.yml
  #ldap:
    #implementation: custom
    #url: ldap://ldap
    #base_dn: dc=example,dc=com
    #additional_users_dn: ou=Users
    #users_filter: (&({username_attribute}={input})(objectClass=inetOrgPerson))
    #username_attribute: uid
    #mail_attribute: mail
      #display_name_attribute: displayName
      #additional_groups_dn: ou=groups
    #groups_filter: (&(member={dn})(objectClass=groupofnames))
    #group_name_attribute: cn
    #user: cn=admin,dc=example,dc=com
    #password: password

access_control:
    default_policy: two_factor

regulation:
    max_retries: 3
    find_time: 2m
    ban_time: 5m

session:
    redis:
        host: redis
        port: 6379
    #consider increasing this
    #https://www.authelia.com/configuration/session/introduction/
    #remember_me_duration:  1M

storage:
    local:
        path: /data/db.sqlite3

notifier:
    # todo use smtp
    filesystem:
        filename: /data/notification.txt

telemetry:
    metrics:
        enabled: true
