networks:
  git_default:
    external: true
  wireguard_default:
    external: true
  minecraft_default:
    external: true
volumes:
  certificates:
services:
  nginx:
    build: ./nginx
    restart: unless-stopped
    depends_on:
      certbot:
        condition: service_healthy
#note that propogating source IP addressed requires "DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=slirp4netns"
    ports:
      - 80:80
      - 443:443
    networks:
      - default
      - git_default
      - wireguard_default
      - minecraft_default
    volumes:
      - certificates:/etc/letsencrypt/
    healthcheck:
# todo remove --insecure on 12/31
      test: [ "CMD-SHELL", "curl --insecure -f https://griffinht.com:443" ]
      interval: 5s
      timeout: 5s
      retries: 5
  certbot:
    build: ./certbot
    restart: unless-stopped
    volumes:
      - certificates:/etc/letsencrypt/
    environment:
      - CERTBOT_CLOUDFLARE=${CERTBOT_CLOUDFLARE?you forgot ./certbot/configure.sh}
    healthcheck:
      test: [ "CMD-SHELL", "ls -f /etc/letsencrypt/live/griffinht.com/fullchain.pem" ]
      interval: 1s
      timeout: 1s
      retries: 60
#  dynamic-ip:
#    build: ./dynamic-ip
#    restart: unless-stopped
#    environment:
#      - DYNAMIC-IP_CLOUDFLARE=${DYNAMIC-IP_CLOUDFLARE?you forgot ./dynamic-ip/configure.sh}
