networks:
  git_internal:
    external: true
  wireguard_default:
    external: true
  minecraft_default:
    external: true
  data_internal:
    external: true
  speedtest_internal:
    external: true
volumes:
  http_certificates:
    external: true
  http_acme:
    external: true
services:
  nginx:
    build: ./nginx
    restart: unless-stopped
    depends_on:
      acme:
        condition: service_healthy
#note that propogating source IP addressed requires "DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=slirp4netns"
    ports:
      - 80:80
      - 443:443
    networks:
      - default
      - git_internal
      - wireguard_default
      - minecraft_default
      - data_internal
      - speedtest_internal
    volumes:
      - http_certificates:/certificates
    healthcheck:
      test: [ "CMD-SHELL", "curl -f https://griffinht.com:443" ]
      interval: 5s
      timeout: 5s
      retries: 5
  acme:
    build: ./acme
    restart: unless-stopped
    volumes:
      - http_certificates:/certificates
      - http_acme:/acme
    environment:
      - CERTBOT_CLOUDFLARE=${CERTBOT_CLOUDFLARE?you forgot ./certbot/configure.sh}
      - CERTBOT_AWS_ACCESS_KEY_ID=${CERTBOT_AWS_ACCESS_KEY_ID?you forgot ./certbot/configure.sh}
      - CERTBOT_AWS_SECRET_ACCESS_KEY=${CERTBOT_AWS_SECRET_ACCESS_KEY?you forgot ./certbot/configure.sh}
    healthcheck:
      test: [ "CMD-SHELL", "ls -f /certificates/griffinht.com/griffinht.com.cer" ]
      interval: 1s
      timeout: 1s
      retries: 60
#  dynamic-ip:
#    build: ./dynamic-ip
#    restart: unless-stopped
#    environment:
#      - DYNAMIC-IP_CLOUDFLARE=${DYNAMIC-IP_CLOUDFLARE?you forgot ./dynamic-ip/configure.sh}
