services:
  nginx:
    depends_on:
      certbot:
        condition: service_healthy
    restart: unless-stopped
    image: nginx
    build:
      context: nginx
    ports:
      - 443:443
    volumes:
      - certbot:/etc/letsencrypt/
    healthcheck:
      test: [ "CMD-SHELL", "curl -f https://griffinht.com:443" ]
      interval: 5s
      timeout: 5s
      retries: 5
  certbot:
    restart: unless-stopped
    image: certbot
    build:
      context: certbot
    environment:
      - CERTBOT_CLOUDFLARE=${CERTBOT_CLOUDFLARE}
    volumes:
      - certbot:/etc/letsencrypt/
    healthcheck:
      test: [ "CMD-SHELL", "ls  -f /etc/letsencrypt/live/griffinht.com/fullchain.pem" ]
      interval: 1s
      timeout: 1s
      retries: 60
  dynamic-ip:
    restart: unless-stopped
    image: dynamic-ip
    build:
      context: dynamic-ip
    environment:
      - DYNAMIC-IP_CLOUDFLARE=${DYNAMIC-IP_CLOUDFLARE}
    volumes:
      - ./dynamic-ip/paths:/paths

volumes:
  certbot: