networks:
  proxied_git:
    external: true
volumes:
  certificates:
services:
  nginx:
    image: nginx
    restart: unless-stopped
    depends_on:
      certbot:
        condition: service_healthy
    build: ./nginx
#note that propogating source IP addressed requires "DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=slirp4netns"
    ports:
      - 80:80
      - 443:443
    networks:
      - default
      - proxied_git
    volumes:
      - certificates:/etc/letsencrypt/
    healthcheck:
# todo remove --insecure on 12/31
      test: [ "CMD-SHELL", "curl --insecure -f https://griffinht.com:443" ]
      interval: 5s
      timeout: 5s
      retries: 5
  certbot:
    image: certbot
    restart: unless-stopped
    build: ./certbot
    volumes:
      - certificates:/etc/letsencrypt/
    environment:
      - CERTBOT_CLOUDFLARE=${CERTBOT_CLOUDFLARE?you forgot ./certbot/configure.sh}
    healthcheck:
      test: [ "CMD-SHELL", "ls -f /etc/letsencrypt/live/griffinht.com/fullchain.pem" ]
      interval: 1s
      timeout: 1s
      retries: 60
#  dynamic-ip:
#    restart: unless-stopped
#    image: dynamic-ip
#    build: ./dynamic-ip
#    environment:
#      - DYNAMIC-IP_CLOUDFLARE=${DYNAMIC-IP_CLOUDFLARE?you forgot ./dynamic-ip/configure.sh}
