services:
  nginx:
    depends_on:
      certbot:
        condition: service_healthy
    restart: unless-stopped
    image: nginx
    build:
      context: nginx
    ports:
      - 443:443
    volumes:
      - certbot:/etc/letsencrypt/
    healthcheck:
      test: [ "CMD-SHELL", "curl -f https://griffinht.com:443" ]
      interval: 5s
      timeout: 5s
      retries: 5
  certbot:
    restart: unless-stopped
    image: certbot
    build:
      context: certbot
    secrets:
      - certbot_cloudflare
    volumes:
      - certbot:/etc/letsencrypt/
    healthcheck:
      test: [ "CMD-SHELL", "ls  -f /etc/letsencrypt/live/griffinht.com/fullchain.pem" ]
      interval: 1s
      timeout: 1s
      retries: 60
  dynamic-ip:
    restart: unless-stopped
    image: dynamic-ip
    build:
      context: dynamic-ip
    secrets:
        - dynamic-ip_cloudflare
    volumes:
      - ./dynamic-ip/paths:/paths

volumes:
  certbot:

secrets:
  certbot_cloudflare:
    file: bin/certbot_cloudflare
  dynamic-ip_cloudflare:
    file: bin/dynamic-ip_cloudflare