networks:
  git_internal:
    external: true
  data_internal:
    external: true
  speedtest_internal:
    external: true
  webdav_internal:
    external: true
  vaultwarden_internal:
    external: true
  registry_internal:
    external: true
  rss_default:
    external: true
  libreddit_default:
    external: true
  nitter_default:
    external: true
  invidious_default:
    external: true
volumes:
  http_certificates:
    external: true
  http_acme:
    external: true
  http_passwd:
    external: true
services:
  # https://github.com/nginxinc/docker-nginx/
  nginx:
    build: ./nginx
    restart: unless-stopped
    depends_on:
      acme:
        condition: service_healthy
#note that propogating source IP addressed requires "DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=slirp4netns"
    ports:
      - 80:80
      - 443:443
    networks:
      - default
      - git_internal
      - data_internal
      - speedtest_internal
      - webdav_internal
      - vaultwarden_internal
      - registry_internal
      - rss_default
      - libreddit_default
      - nitter_default
      - invidious_default
    volumes:
      - http_certificates:/certificates:ro
      - http_passwd:/passwd:ro
    healthcheck:
      test: [ "CMD-SHELL", "curl -f https://griffinht.com:443" ]
      interval: 5s
      timeout: 5s
      retries: 5
  acme:
    # https://github.com/acmesh-official/acme.sh/
    image: neilpang/acme.sh:3.0.4@sha256:c9b93d808ca8019ed9867f211f17bb5506d86bbb0d2e46b2ac26b368ce3fee95
    restart: unless-stopped
    volumes:
      - http_certificates:/certificates
      - http_acme:/acme
    environment:
      - CF_Token=${CERTBOT_CLOUDFLARE?you forgot to configure Cloudflare see README}
      - AWS_ACCESS_KEY_ID=${CERTBOT_AWS_ACCESS_KEY_ID?you forgot to configure AWS Route53 see README}
      - AWS_SECRET_ACCESS_KEY=${CERTBOT_AWS_SECRET_ACCESS_KEY?you forgot to configure AWS Route53 see README}
    command: daemon --issue --cert-home /certificates --config-home /acme --server letsencrypt -d 'griffinht.com' --dns dns_cf -d '*.griffinht.com' --dns dns_cf -d 'stzups.net' --dns dns_cf -d 'griffin.ht' --dns dns_aws
    healthcheck:
      test: [ "CMD", "ls", "/certificates/griffinht.com/griffinht.com.cer" ]
      interval: 1s
      timeout: 1s
      retries: 60
#  dynamic-ip:
#    build: ./dynamic-ip
#    restart: unless-stopped
#    environment:
#      - DYNAMIC-IP_CLOUDFLARE=${DYNAMIC-IP_CLOUDFLARE?you forgot ./dynamic-ip/configure.sh}
