- name: Install Docker on Debian
  hosts: compose
  user: root
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io
          # todo remove???
        #- wireguard-tools
        #- prometheus-node-exporter
          #https://www.syslog-ng.com/community/b/blog/posts/sending-logs-from-syslog-ng-to-grafana-loki
          ##https://alexandre.deverteuil.net/post/syslog-relay-for-loki/
