- name: Install Docker on Debian
  hosts: docker
  user: root

  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io
        - wireguard-tools
