networks:
    internal:
        driver: bridge
        internal: true
    http_default:
        external: true
volumes:
    prometheus:
        external: true
services:
    prometheus:
        build: .
        restart: unless-stopped
        networks:
            - internal
        volumes:
            - prometheus:/prometheus
    node_exporter:
        image: quay.io/prometheus/node-exporter:latest
        restart: unless-stopped
        networks:
            - internal
        command:
          - '--path.rootfs=/host'
        pid: host
        volumes:
          - '/:/host:ro,rslave'
    nginx_exporter:
        image: nginx/nginx-prometheus-exporter
        restart: unless-stopped
        networks:
            - internal
            - http_default
        command: -nginx.scrape-uri=http://nginx:8080
