networks:
    internal:
        driver: bridge
        internal: true
volumes:
    vaultwarden:
        external: true
services:
    vaultwarden:
        image: vaultwarden/server:alpine
        restart: unless-stopped
        volumes:
            - vaultwarden:/data
        networks:
            - internal
        environment:
            WEBSOCKET_ENABLED: true
            DOMAIN: https://cold.griffinht.com/bitwarden/
            # needed for TOTP
            TZ: America/New_York
            # no internet so this will fail anyway
            DISABLE_ICON_DOWNLOAD: true
