networks:
    internal:
        driver: bridge
        internal: true
volumes:
    vaultwarden:
        external: true
services:
    # https://github.com/dani-garcia/vaultwarden/
    # https://hub.docker.com/r/vaultwarden/server/tags
    vaultwarden:
        image: vaultwarden/server:alpine@sha256:7011d4216a00fcd79785b8b31d61b897e05d959aa37681323dd9c0155655bbbc
        restart: unless-stopped
        volumes:
            - vaultwarden:/data
        networks:
            - internal
        environment:
            WEBSOCKET_ENABLED: true
            DOMAIN: https://cold.griffinht.com/bitwarden/
            # needed for TOTP
            TZ: America/New_York
            # no internet so this will fail anyway
            DISABLE_ICON_DOWNLOAD: true
