volumes:
  griffinht:
    external: true

networks:
  internal:
    driver: bridge
    internal: true

services:
  griffinht:
    # todo use guix python
    image: localhost/python:latest
    command: python3 -m http.server --directory /serve 80
    volumes:
      - griffinht:/serve:ro
    networks:
      - internal
  git:
    image: localhost/gitwebui:latest
    command: run.sh
      #    user: nobody
      #user: 65534:996
      #user: root
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    networks:
      - internal
