volumes:
  git:
services:
  git-http-backend:
    build: ./git-http-backend
    restart: unless-stopped
    volumes:
      - git:/git
  git-http-frontend:
    image: git-web-view:latest
    restart: unless-stopped
    volumes:
      - git:/git
    command: --directory /git