networks:
  git:
volumes:
  git:
services:
  git-nginx:
    build: ./nginx
    depends_on:
      - git-http-backend
      - git-http-frontend
    restart: unless-stopped
    networks:
      - git
  git-http-backend:
    build: ./git-http-backend
    restart: unless-stopped
    networks:
      - git
    volumes:
      - git:/git
  git-http-frontend:
    build: ./git-http-frontend
    restart: unless-stopped
    networks:
      - git
    volumes:
      - git:/git