volumes:
  git:
services:
  git-http-backend:
    build: ./git-http-backend
    restart: unless-stopped
    volumes:
      - git:/git
  git-http-frontend:
    build: ./git-http-frontend
    restart: unless-stopped
    volumes:
      - git:/git