# fly.toml app configuration file generated for flydfsg on 2024-05-28T12:38:32-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flydfsg'
primary_region = 'iad'

# todo change build to image
[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
    RUN_MIGRATIONS=1
