# fly.toml app configuration file generated for flydfsg on 2024-05-28T12:38:32-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flydfsg'
primary_region = 'iad'

# todo change build to image
[build]
  image = 'docker.io/miniflux/miniflux:latest'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

# https://miniflux.app/docs/configuration.html
[env]
#    RUN_MIGRATIONS=1
    AUTH_PROXY_HEADER = 'X-Forwarded-User'
    AUTH_PROXY_USER_CREATION = 'true'
#    METRICS_COLLECTOR=true
#    METRICS_USERNAME=bruh

#CREATE_ADMIN=1
#ADMIN_USERNAME=admin
