networks:
    internal:
        driver: bridge
        external: false
volumes:
    matrix:
        external: true
services:
    matrix: 
        image: registry.gitlab.com/famedly/conduit/matrix-conduit
        restart: unless-stopped
        networks:
            - internal
        volumes:
            - matrix:/var/lib/matrix-conduit
    postgres:
        build: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_USER=dendrite
            - POSTGRES_PASSWORD=passwordexample
        volumes:
            - matrix:/var/lib/postgresql/data
        networks:
            - internal
        healthcheck: 
            test: ["CMD", "pg_isready", "-U", "dendrite"]
            interval: 10s
            start_period: 30s
