networks:
  internal:
    driver: bridge
    internal: true
  redis:
    driver: bridge
    internal: true

volumes:
  authelia_internal:
  authelia:
    external: true

services:
    authelia:
        build: authelia
        restart: unless-stopped
        depends_on:
            redis:
                condition: service_healthy
        networks:
            - internal
            - redis
        environment: 
            - AUTHELIA_JWT_SECRET_FILE=/data/jwt_secret
            - AUTHELIA_SESSION_SECRET_FILE=/data/session.secret
            - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/data/storage.encryption_key
            # todo restrict so not every backend server gets the session cookie
            - "AUTHELIA_SESSION_DOMAIN=${DOMAIN:-hot.localhost}"
        volumes:
            - authelia:/data
              # volume declared by authelia
            - authelia_internal:/config
    redis:
        image: redis:alpine
        restart: unless-stopped
        networks:
            - redis
        volumes:
            - authelia:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5
