#https://forums.docker.com/t/top-level-volume-with-absolute-path/27552
#https://stackoverflow.com/questions/53674725/how-to-create-top-level-named-volume-with-a-relative-path-for-the-source
# i had to add type: volume for some reason idk why
volumes:
  authelia:
  authelia_secrets:
    driver: local
    driver_opts:
      device: ./mock
      o: bind
      type: volume

secrets:
  authelia_session:
    file: ./mock/authelia_session
  authelia_jwt:
    file: ./mock/authelia_jwt
  authelia_storage:
    file: ./mock/authelia_storage

services:
  authelia:
    environment:
      - AUTHELIA_ACCESS_CONTROL_DEFAULT_POLICY=one_factor
    volumes:
      - authelia_secrets:/secrets:ro
