networks:
  internal:
    driver: bridge
    internal: true
  redis:
    driver: bridge
    internal: true
  #ldap_internal:
    #external: true

volumes:
  authelia_internal:
  authelia:
    external: true


secrets:
  authelia_session:
    file: /home/docker-user/secrets/authelia_session
  authelia_jwt:
    file: /home/docker-user/secrets/authelia_jwt
  authelia_storage:
    file: /home/docker-user/secrets/authelia_storage

services:
    authelia:
        build: authelia
        restart: always
        depends_on:
            redis:
                condition: service_healthy
        networks:
            - internal
            - redis
            #- ldap_internal
          # todo undo
        environment: 
          - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session
          - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt
          - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/authelia_storage
          - "AUTHELIA_SESSION_DOMAIN=${DOMAIN:-hot.localhost}"
            # todo restrict so not every backend server gets the session cookie
        volumes:
            - authelia:/data
              # volume declared by authelia
            - authelia_internal:/config
        secrets:
          - authelia_session
          - authelia_jwt
          - authelia_storage
    redis:
        image: redis:alpine
        restart: always
        networks:
            - redis
        volumes:
            - authelia:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5
