networks:
  internal:
    driver: bridge
    internal: true
services:
  iperf3:
    build: ./iperf3
    restart: unless-stopped
    networks:
        - internal
    ports:
      - 5201:5201/udp
      - 5201:5201/tcp
