networks:
  internal:
    driver: bridge
    internal: true
services:
  # https://github.com/librespeed/speedtest/
  speedtest:
    image: adolfintel/speedtest@sha256:1f828fe8337470d2ed5841176bfa6633fd94bda97261a636c35d0bef60a35270
    restart: unless-stopped
    networks:
      - internal
