volumes:
  data_internal:

networks:
    internal:
        driver: bridge
        internal: true

services:
    nitter:
        build: ./nitter
        restart: always
        networks:
            - default
            - internal
    redis:
        image: redis:alpine@sha256:a22bc2d15940ae67680611827b3e9b69150d7c11c063415c3775c35d163bb555
        restart: always
        networks:
            - internal
        volumes:
          - data_internal:/data
