volumes:
  mock_lego:
  https_lego:
  https_certificates:

services:
  # https://github.com/nginxinc/docker-nginx/
  nginx:
    volumes:
      - mock_lego:/certificates
    depends_on:
      lego:
        condition: service_completed_successfully
  lego:
    build: mock/lego
    command: ""
    volumes: 
      - mock_lego:/lego/certificates
    environment:
      - CF_ZONE_API_TOKEN
      - CF_DNS_API_TOKEN
