# https://stackoverflow.com/questions/53751168/docker-compose-secrets-without-swarm
# todo mock https certs
networks:
  hot_internal:
    external: true
  griffinht_internal:
    external: true
volumes:
  https_certificates:
    external: true
  https_lego:
    external: true
services:
  # https://github.com/nginxinc/docker-nginx/
  nginx:
    build: ./nginx
    restart: unless-stopped
    depends_on:
      lego:
        condition: service_healthy
    #note that propogating source IP addressed requires "DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=slirp4netns"
    ports:
      - 80:80
      - 443:443
    networks:
      - default
      - hot_internal
      - griffinht_internal
    volumes:
      - https_certificates:/certificates:ro
    healthcheck:
    # todo this won't really work
      test: [ "CMD-SHELL", "curl -f https://griffinht.com:443" ]
      interval: 5s
      timeout: 5s
      retries: 5
  lego:
    build: mock/lego 
      # https://github.com/go-acme/lego/pull/1378
      #    command: --accept-tos --email bruhacme@griffinht.com -dns cloudflare --domains griffinht.com todo *.griffinht.com --server=https://acme-staging-v02.api.letsencrypt.org/directory --path /lego run
    volumes: 
      - https_lego:/lego
      - https_certificates:/certificates
    healthcheck:
      test: [ "CMD", "ls", "/certificates/griffinht.com/griffinht.com.key" ]
      interval: 5s
      timeout: 5s
      retries: 5
