# https://stackoverflow.com/questions/53751168/docker-compose-secrets-without-swarm
#      todo
      #      depends_on:
      #  lego:
      #    condition: service_completed_successfully
  #note that propogating source IP addressed to nginx requires "DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=slirp4netns"
networks:
  hot_internal:
    name: hot_internal
  griffinht_internal:
    name: griffinht_internal
volumes:
  https_certificates:
    external: true
  https_lego:
    external: true
services:
  # https://github.com/nginxinc/docker-nginx/
  nginx:
    build: nginx
    restart: always
    ports:
      - "${BIND_ADDRESS:-127.0.0.1}:${BIND_PORT_HTTP:-8000}:80"
      - "${BIND_ADDRESS:-127.0.0.1}:${BIND_PORT_HTTPS:-4430}:443"
    environment:
      - "NGINX_DOMAIN=${DOMAIN:-localhost}"
      - "NGINX_RESOLVER=${RESOLVER:-10.89.0.1}"
    networks:
      #todo what is this
      #its needed for docker (ports don't expose without it)
      #but podman it breaks things (it doesn't exist)
      - default
      - hot_internal
      - griffinht_internal
    volumes:
      - https_certificates:/certificates:ro
    healthcheck:
    # todo this won't really work
    # actually it does, why wouldn't it work?
      test: [ "CMD-SHELL", "curl -f https://griffinht.com:443" ]
      interval: 5s
      timeout: 5s
      retries: 5
  lego:
    #todo restart policy?
    #todo automate cron??
    image: goacme/lego 
      # https://github.com/go-acme/lego/pull/1378
    command: --accept-tos --email bruhacme@griffinht.com -dns cloudflare --domains "griffinht.com" --domains "*.griffinht.com" --domains "*.hot.griffinht.com" --path /lego renew
    volumes: 
      - https_lego:/lego
    environment:
      - CF_ZONE_API_TOKEN=${CF_ZONE_API_TOKEN?you forgot to configure Cloudflare see README}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN?you forgot to configure Cloudflare see README}
    healthcheck:
      test: [ "CMD", "ls", "/certificates/griffinht.com.crt" ]
      interval: 5s
      timeout: 5s
      retries: 5
