# https://stackoverflow.com/questions/53751168/docker-compose-secrets-without-swarm
# todo mock https certs
networks:
  hot_internal:
    external: true
  griffinht_internal:
    external: true
volumes:
  https_certificates:
    external: true
  https_lego:
    external: true
services:
  # https://github.com/nginxinc/docker-nginx/
  nginx:
    build: nginx
    restart: unless-stopped
      #      depends_on:
      #  lego:
      #    condition: service_completed_successfully
    #note that propogating source IP addressed requires "DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=slirp4netns"
    ports:
      - "${BIND_ADDRESS:-127.0.0.1}:80:80"
      - "${BIND_ADDRESS:-127.0.0.1}:443:443"
    environment:
      - DOMAIN="${DOMAIN:-localhost}"
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template.conf
      - NGINX_ENVSUBST_FILTER=DOMAIN
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/
    networks:
      - default
      - hot_internal
      - griffinht_internal
    volumes:
      - https_certificates:/certificates:ro
    healthcheck:
    # todo this won't really work
      test: [ "CMD-SHELL", "curl -f https://griffinht.com:443" ]
      interval: 5s
      timeout: 5s
      retries: 5
  lego:
    #todo automate cron??
    image: goacme/lego 
      # https://github.com/go-acme/lego/pull/1378
    command: --accept-tos --email bruhacme@griffinht.com -dns cloudflare --domains "griffinht.com" --domains "*.griffinht.com" --path /lego renew
    volumes: 
      - https_lego:/lego
    environment:
      - CF_ZONE_API_TOKEN=${CF_ZONE_API_TOKEN?you forgot to configure Cloudflare see README}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN?you forgot to configure Cloudflare see README}
    healthcheck:
      test: [ "CMD", "ls", "/certificates/griffinht.com.crt" ]
      interval: 5s
      timeout: 5s
      retries: 5
