# https://stackoverflow.com/questions/53751168/docker-compose-secrets-without-swarm
# todo mock https certs
networks:
 http_default:
      external: true
volumes:
  http_certificates:
    external: true
  lego:
    external: true
services:
  # https://github.com/nginxinc/docker-nginx/
  nginx:
  build: ./nginx
    restart: unless-stopped
    #    depends_on:
    #      acme:
    #        condition: service_healthy
    #note that propogating source IP addressed requires "DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=slirp4netns"
    ports:
      - 80:80
      - 443:443
    networks:
      - default
      - http_default
    volumes:
      - http_certificates:/certificates:ro
    healthcheck:
    # todo this won't really work
      test: [ "CMD-SHELL", "curl -f https://griffinht.com:443" ]
      interval: 5s
      timeout: 5s
      retries: 5
  lego:
    image: goacme/lego
    command: -H --path /lego
    volumes: 
      - lego:/lego
        #https://go-acme.github.io/lego/usage/cli/obtain-a-certificate/
