volumes:
  invidious:
  invidious_postgres_config:
  invidious_postgres_entrypoint:

networks:
  internal:
    driver: bridge
    internal: true

services:
  invidious:
    image: quay.io/invidious/invidious:latest
    restart: unless-stopped
    networks:
      - default
      - internal
    ports:
      - 3000:3000
    environment:
      INVIDIOUS_CONFIG: |
        database_url: postgres://postgres:@postgres
        hmac_key: b7377837040574d07a254cb89b6f7e014b14386c
    depends_on:
      - postgres
  # todo use guix?
  postgres:
    image: docker.io/library/postgres
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - invidious:/var/lib/postgresql/data
      - invidious_postgres_config:/config/sql:ro
      - invidious_postgres_entrypoint:/docker-entrypoint-initdb.d/init-invidious-db.sh:ro
        #- ./invidious/config/sql:/config/sql:ro
        #- ./invidious/docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh:ro
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
