networks:
  traefik_default:
    external: true

      # port 8080
services:
  dozzle:
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik_default
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
    labels:
      - traefik.enable=true
      - traefik.http.services.dozzle-dozzle.loadbalancer.healthcheck.path=/
