# https://docs.docker.com/config/daemon/prometheus/
volumes:
  prometheus:
  xmpp-alerts-password:

networks:
  internal:
    driver: bridge
    internal: true

services:

  prometheus:
    image: docker.io/prom/prometheus
    depends_on:
      - blackbox_exporter
      - alertmanager
    networks:
      - internal
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./prometheus.yml:/config/prometheus.yml:ro
      - prometheus:/prometheus
    command: --config.file=/config/prometheus.yml

  blackbox_exporter:
    image: quay.io/prometheus/blackbox-exporter:latest
    networks:
      - internal
      - default
    ports:
      - 127.0.0.1:9115:9115

  alertmanager:
    image: quay.io/prometheus/alertmanager:latest
    depends_on:
      - xmpp-alerts
    networks:
      - internal
    ports:
      - 127.0.0.1:9093:9093
    volumes:
      - ./alertmanager.yml:/config/alertmanager.yml:ro
    command: --config.file=/config/alertmanager.yml

  xmpp-alerts:
    image: ghcr.io/jelmer/prometheus-xmpp-alerts
    networks:
      - internal
      - default
    ports:
      - 127.0.0.1:9199:9199
    volumes:
      - ./xmpp-alerts.yml:/config.yaml:ro
        # todo
      - xmpp-alerts-password:/secrets:ro

  caddy:
    image: docker.io/caddy
    networks:
      - internal
    ports:
      - 8080:80
      - 4434:443
      - 127.0.0.1:2019:2019
    environment:
      DOMAIN: localhost
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./html:/usr/share/caddy:ro

# todo cadvisor?
