# https://docs.docker.com/config/daemon/prometheus/
volumes:
  prometheus:
  prometheus_config:
  alertmanager_config:
  xmpp-alerts_password:
  xmpp-alerts_config:
  caddy_config:
  caddy_html:

networks:
  internal:
    driver: bridge
    internal: true

services:

  prometheus:
    image: docker.io/prom/prometheus
    restart: unless-stopped
    depends_on:
      - blackbox_exporter
      - alertmanager
    networks:
      #- internal
      - default
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - prometheus_config:/config:ro
      - prometheus:/prometheus
        # the url to open the Prometheus instance, shown in alerts
    command: --config.file=/config/prometheus.yml --web.external-url=http://nerd-vps.wg.hot.griffinht.com:9090

  blackbox_exporter:
    image: quay.io/prometheus/blackbox-exporter:latest
    networks:
      #- internal
      - default
    ports:
      - 127.0.0.1:9115:9115

  alertmanager:
    image: quay.io/prometheus/alertmanager:latest
    depends_on:
      - xmpp-alerts
    networks:
      #- internal
      - default
    ports:
      - 127.0.0.1:9093:9093
    volumes:
      - alertmanager_config:/config:ro
        # todo what does this do? --web.external-url
    command: --config.file=/config/alertmanager.yml --web.external-url=http://localhosttodo:123

  xmpp-alerts:
    image: ghcr.io/jelmer/prometheus-xmpp-alerts
    networks:
      #- internal
      - default
    ports:
      - 127.0.0.1:9199:9199
    volumes:
      - xmpp-alerts_config:/config:ro
        # todo
      - xmpp-alerts_password:/secrets:ro
    command: python3 -m prometheus_xmpp --config=/config/xmpp-alerts.yml

  caddy:
    image: docker.io/caddy
    restart: unless-stopped
    networks:
      #- internal
      - default
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:2019:2019
    environment:
      DOMAIN: status.griffinht.com
    volumes:
      - caddy_config:/etc/caddy:ro
      - caddy_html:/usr/share/caddy:ro

# todo cadvisor?
