# https://docs.docker.com/config/daemon/prometheus/
volumes:
  prometheus:
  prometheus_config:
  alertmanager_config:
  xmpp-alerts_password:
  xmpp-alerts_config:
  caddy_config:
  caddy_html:

networks:
  internal:
    driver: bridge
    internal: true

services:

  prometheus:
    image: docker.io/prom/prometheus
    depends_on:
      - blackbox_exporter
      - alertmanager
    networks:
      - internal
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - prometheus_config:/config:ro
      - prometheus:/prometheus
    command: --config.file=/config/prometheus.yml

  blackbox_exporter:
    image: quay.io/prometheus/blackbox-exporter:latest
    networks:
      - internal
      - default
    ports:
      - 127.0.0.1:9115:9115

  alertmanager:
    image: quay.io/prometheus/alertmanager:latest
    depends_on:
      - xmpp-alerts
    networks:
      - internal
    ports:
      - 127.0.0.1:9093:9093
    volumes:
      - alertmanager_config:/config:ro
    command: --config.file=/config/alertmanager.yml

  xmpp-alerts:
    image: ghcr.io/jelmer/prometheus-xmpp-alerts
    networks:
      - internal
      - default
    ports:
      - 127.0.0.1:9199:9199
    volumes:
      - xmpp-alerts_config:/config:ro
        # todo
      - xmpp-alerts_password:/secrets:ro
    command: python3 -m prometheus_xmpp --config=/config/xmpp-alerts.yml

  caddy:
    image: docker.io/caddy
    networks:
      - internal
    ports:
      - 8080:80
      - 4434:443
      - 127.0.0.1:2019:2019
    environment:
      DOMAIN: localhost
    volumes:
      - caddy_config:/etc/caddy:ro
      - caddy_html:/usr/share/caddy:ro

# todo cadvisor?
