global:
  scrape_interval: 1s
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: griffinht.com
  metrics_path: /probe
  params:
    target: [griffinht.com]
    module: [http_2xx]
  static_configs:
  - targets:
    - blackbox_exporter:9115
- job_name: blackbox_exporter
  metrics_path: /metrics
  static_configs:
  - targets:
    - blackbox_exporter:9115
