volumes:
    ssh:
    ssh_authorized:
services:
    git:
        build: git
        ports:
            - 5443:22
        volumes:
            - ssh_authorized:/home/git/.ssh/:ro
            - ssh:/ssh
