volumes:
    ssh:
        external: true
    ssh_authorized_keys:
        external: true
    git:
        external: true
    ci:
services:
    git:
        build: git
        ports:
            - 5443:22
        restart: unless-stopped
        volumes:
            - ssh_authorized_keys:/home/git/.ssh/:ro
            - ssh:/ssh
            - git:/git
            - ci:/ci
    ci:
        image: griffinht/firestarter
        restart: unless-stopped
        volumes:
            - ci:/ci
