global:
  scrape_interval: 15s

scrape_configs:
- job_name: node
  static_configs:
  - targets: ['node_exporter:9100']
- job_name: nginx
  static_configs:
  - targets: ['nginx_exporter:9113']
- job_name: authelia
  static_configs:
  - targets: ['authelia:9959']
- job_name: cadvisor
  static_configs:
  - targets: ['cadvisor:8080']
- job_name: blackbox
  metrics_path: /metrics
  static_configs:
  - targets: ['blackbox:9115']
- job_name: blackbox-http
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - http://griffinht.com
      - https://griffinht.com
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115
