global:
  scrape_interval: 15s

scrape_configs:
- job_name: node
  static_configs:
  - targets: ['node_exporter:9100']
- job_name: nginx
  static_configs:
  - targets: ['nginx_exporter:9113']
- job_name: authelia
  static_configs:
  - targets: ['authelia:9959']
- job_name: cadvisor
  static_configs:
  - targets: ['cadvisor:8080']
