networks:
  internal:
    driver: bridge
    internal: true
  nginx_exporter:
    driver: bridge
    internal: true
  data_internal:
    name: data_internal
  speedtest_internal:
    name: speedtest_internal
  vaultwarden_internal:
    name: vaultwarden_internal
  rss_default:
    name: rss_default
  libreddit_default:
    name: libreddit_default
  nitter_default:
    name: nitter_default
  invidious_default:
    name: invidious_default
  searx_default:
    name: searx_default
  scribe_default:
    name: scribe_default
  rimgo_default:
    name: rimgo_default
  quetre_default:
    name: quetre_default
  grocy_internal:
    name: grocy_internal
  photoprism_internal:
    name: photoprism_internal
  authelia_internal:
    name: authelia_internal
      #  grafana_internal:
      #    external: true
services:
  # https://github.com/nginxinc/docker-nginx/
  hot:
      build: ./nginx
      restart: unless-stopped
      networks:
        - internal
        - data_internal
        - speedtest_internal
        - vaultwarden_internal
        - rss_default
        - libreddit_default
        - nitter_default
        - invidious_default
        - searx_default
        - scribe_default
        - rimgo_default
        - quetre_default
        - grocy_internal
        - photoprism_internal
        - authelia_internal
          #        - grafana_internal
      environment:
        - "DOMAIN=${DOMAIN:-localhost}"
  nginx_exporter:
      image: nginx/nginx-prometheus-exporter
      restart: unless-stopped
      depends_on:
          - hot
              #                condition: service_healthy
      networks:
        # why default network?
          - default
          - nginx_exporter
      command: -nginx.scrape-uri=http://nginx:8080
  blackbox:
      image: prom/blackbox-exporter
      restart: unless-stopped
      depends_on:
          - hot
      networks:
        # why default network?
          - default
          - nginx_exporter
