networks:
  internal:
    driver: bridge
    internal: true
  nginx_exporter:
    driver: bridge
    internal: true
  data_internal:
    external: true
  speedtest_internal:
    external: true
  vaultwarden_internal:
    external: true
  rss_default:
    external: true
  libreddit_default:
    external: true
  nitter_default:
    external: true
  invidious_default:
    external: true
  searx_default:
    external: true
  scribe_default:
    external: true
  rimgo_default:
    external: true
  quetre_default:
    external: true
  grocy_internal:
    external: true
  photoprism_internal:
    external: true
  authelia_internal:
    external: true
      #  grafana_internal:
      #    external: true
services:
  # https://github.com/nginxinc/docker-nginx/
  hot:
      build: ./nginx
      restart: unless-stopped
      networks:
        - internal
        - data_internal
        - speedtest_internal
        - vaultwarden_internal
        - rss_default
        - libreddit_default
        - nitter_default
        - invidious_default
        - searx_default
        - scribe_default
        - rimgo_default
        - quetre_default
        - grocy_internal
        - photoprism_internal
        - authelia_internal
          #        - grafana_internal
      environment:
        - "DOMAIN=${DOMAIN:-localhost}"
  nginx_exporter:
      image: nginx/nginx-prometheus-exporter
      restart: unless-stopped
      depends_on:
          - hot
              #                condition: service_healthy
      networks:
        # why default network?
          - default
          - nginx_exporter
      command: -nginx.scrape-uri=http://nginx:8080
  blackbox:
      image: prom/blackbox-exporter
      restart: unless-stopped
      depends_on:
          - hot
      networks:
        # why default network?
          - default
          - nginx_exporter
