volumes:
  minecraft:
    external: true
services:
  minecraft:
    restart: unless-stopped
    build: ./minecraft
    stop_grace_period: 60s
    ports:
      - 25565:25565
    environment:
        WEB:
        WEB_BASE_PATH: /minecraft
    volumes:
      - minecraft:/minecraft
