#todo
#volumes:
  #  git:

networks:
  internal:
    driver: bridge
    internal: true

services:
  git:
    image: gitwebui
    command: run.sh
      #    user: nobody
      #user: 65534:996
      #user: root
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    networks:
      - internal
