volumes:
  tailscale:

services:
  postgres:
    image: tailscale/tailscale
    hostname: postgres
    #privileged: true
    #network_mode: host
    environment:
      - TS_DEST_IP=34.138.68.188
      - TS_USERSPACE=false
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - tailscale:/var/lib/tailscale
    cap_add:
      - NET_ADMIN
