volumes:
  wireguard_wg-access-server-data:
    external: true
services:
  wireguard:
    build: ./wireguard
    restart: unless-stopped
    cap_add:
        - NET_ADMIN
    ports:
        - "3108:3108/udp"
    volumes:
        - "wireguard_wg-access-server-data:/data"
    devices:
        - "/dev/net/tun:/dev/net/tun"
