networks:
    internal:
        driver: bridge
        internal: true
volumes:
    wireguard_wg-access-server-data:
        external: true
    wireguard:
        external: true
services:
    wireguard:
        build: ./wireguard
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        ports:
            - "3108:3108/udp"
        volumes:
            - "wireguard_wg-access-server-data:/data"
        devices:
            - "/dev/net/tun:/dev/net/tun"
    wireguard2:
        image: weejewel/wg-easy:latest@sha256:da2b59380880df503fac00a759e860897ea266fabcffad82b0770acbb7b5f0e5
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
            - net.ipv4.ip_forward=1
        networks:
            - internal
        volumes:
            - wireguard:/etc/wireguard
        ports:
            - 51820:51820/udp
        environment:
            - WG_HOST=hot.griffinht.com
            - WG_DEFAULT_DNS=192.168.0.1
