volumes:
  wg-access-server-data:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.0.6,rw
      device: ":/docker/wireguard_wg-access-server-data"
services:
  wireguard:
    build: ./wireguard
    restart: unless-stopped
    cap_add:
        - NET_ADMIN
    ports:
        - "3108:3108/udp"
    volumes:
        - "wg-access-server-data:/data"
    devices:
        - "/dev/net/tun:/dev/net/tun"
