services:
  wireguard:
    build: ./wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - "wg-access-server-data:/data"
    ports:
      - "3108:3108/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"

# shared volumes with the host
volumes:
  wg-access-server-data:
    driver: local
