volumes:
    wireguard:
        external: true
services:
    wireguard:
        image: lscr.io/linuxserver/wireguard:latest
        restart: always
        cap_add:
            - NET_ADMIN
        environment:
            - SERVERURL=hot.griffinht.com
            - PEERS=4
        volumes:
            - wireguard:/config
        ports:
            - 51820:51820/udp
