volumes:
    wireguard:
        external: true
services:
    wireguard:
        build: ./wireguard
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
#        sysctls:
#            - net.ipv4.conf.all.src_valid_mark=1
