#!/bin/sh

set -xe

echo

job="$(mktemp -d)"

# todo what if unset
head -c "$CONTENT_LENGTH" > "$job/run"
chmod +x "$job/run"
"$job/run" > "$job/stdout" 2> "$job/stderr" &
#echo asfsdf > "$job/stdout" 2> "$job/stderr" &
pid="$!"
echo "$pid" > "$job/pid"
echo "$job"
# todo detach or something?

exitcode=0
wait "$pid" || exitcode="$?"
echo "$exitcode" > "$job/exitcode"
