# https://github.com/meichthys/foss_photo_libraries?tab=readme-ov-file
volumes:
  photoprism_mariadb:
  photoprism:
  photoprism_data:
    driver_opts:
      type: cifs
      o: username=bruh,password=
      device: //192.168.0.5/bruhbruh/MEENA/archive

services:
  immich:
    image: ghcr.io/immich-app/immich-server
    command: ['start.sh', 'immich']
    volumes:
      - photoprism_data:/usr/src/app/upload:ro
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    environment:
      - IMMICH_VERSION: postgres
    redis:
      image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    database:
      image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
      environment:
        POSTGRES_PASSWORD: DB_PASSWORD
        POSTGRES_USER: DB_USERNAME
        POSTGRES_DB: DB_DATABASE_NAME

  photoprism:
    image: docker.io/photoprism/photoprism:latest
    depends_on:
      - mariadb
    ports:
      - 2342:2342
    environment:
      # https://dl.photoprism.app/docker/docker-compose.yml
      PHOTOPRISM_READONLY: true
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: "insecure"       # MariaDB or MySQL database user password
      PHOTOPRISM_AUTH_MODE: public
    volumes:
      - photoprism_data:/photoprism/originals:ro
      - photoprism:/photoprism/storage
  mariadb:
    image: docker.io/mariadb:11
    command: --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - photoprism_mariadb:/var/lib/mysql
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: "photoprism"
      MARIADB_PASSWORD: "insecure"
      MARIADB_ROOT_PASSWORD: "insecure"
