networks:
  actualbudget_default:
    name: actualbudget_default
    external: true

volumes:
  caddy:
  caddy_config:

services:
  caddy:
    image: docker.io/caddy
    ports:
      - ${HTTP_PORT:-8080}:80
      - ${HTTPS_PORT:-4443}:443
    networks:
      - default
      - actualbudget_default
    environment:
      - DOMAIN=${DOMAIN:-localhost}
    volumes:
      - caddy_config:/etc/caddy:ro
      - caddy:/data
  tailscale:
    image: docker.io/tailscale/tailscale:latest
    network_mode: service:caddy
    environment:
      - asdf=
