---
- name: the cloud
  hosts: cloud
  user: admin
  become_method: sudo
  become_user: root
  become: true

  tasks:
    - name: install stuff
      apt:
        name: wireguard-tools
        state: present
    - name: copy files todo remove
      copy:
        src: files
        dest: /root
    - name: wg-easy
      #todo dont change dir
      # error on undefined env
      shell:
        chdir: /root/files
        cmd: echo "{{ lookup('ansible.builtin.env', 'PUBKEY', default=Undefined) }}" > pubkey
        creates: pubkey
    - name: fetch server public key
      fetch:
        dest: pubkey
        src: /root/files/pubkey
