---
- name: the cloud
  hosts: cloud
  user: admin
  become_method: sudo
  become_user: root
  become: true

  tasks:
    - name: install tools
      apt:
        name: wireguard-tools
        state: present
    - name: copy files
      copy:
        src: files
        dest: /root
        mode: preserve
    - name: configure wireguard
      register: pubkey
      command:
        chdir: /root
        cmd: ./files/wg0.sh "{{ lookup('ansible.builtin.env', 'PUBKEY', default=Undefined) }}"
        creates: /etc/wireguard/wg0.conf
    - debug:
        msg: "{{ pubkey.stdout }}"
